export const USER_REQUEST_TYPE = {
  REQUEST: "USER_REQUEST",
  SUCCESS: "USER_SUCCESS",
  FAIL: "USER_FAIL"
}

export const STARRED_REPO_REQUEST_TYPE = {
  REQUEST: "STARRED_REPO_REQUEST",
  SUCCESS: "STARRED_REPO_SUCCESS",
  FAIL: "STARRED_REPO_FAIL"
}

export const REPO_REQUEST_TYPE = {
  REQUEST: "REPO_REQUEST",
  SUCCESS: "REPO_SUCCESS",
  FAIL: "REPO_FAIL"
}

export const STARGAZERS_REQUEST_TYPE = {
  REQUEST: "STARGAZERS_REQUEST",
  SUCCESS: "STARGAZERS_SUCCESS",
  FAIL: "STARGAZERS_FAIL"
}

export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE"